layout_spectrum: 0
typography_spectrum: 0.08960573
color:
  saturation: 0.7266159
  lightness: 0.9443148
  brandStrength: 0.7885305
  brandColors:
    - '#00A3C3'
    - '#FEFEFE'
    - '#006A7F'
    - '#B2DBE8'
    - '#57B9D1'
  rhythmicContrast: 0.9349393
name: pulloutplus
